# https://www.baeldung.com/ops/docker-compose-communication
# Before, type: docker network create network-example

version: '3'

services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 8501:8501
    
    environment:
      - DATABASE_SERVER=sql3
      - DATABASE_NAME=sys
      - DATABASE_USERNAME=SA
      - DATABASE_PASSWORD=Thomaseric_97480
    networks:
      - external-example

  sql3:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Thomaseric_97480
    container_name: sql3
    hostname: sql3
    ports:
      - 1433:1433
    networks:
      - external-example
  


networks:
  external-example:
    external: true