# https://www.baeldung.com/ops/docker-compose-communication

# TODO: From link above, apply change in this file to not use 
# the command docker network create AdventureWorksDashboardNetwork

# Before, type: docker network create AdventureWorksDashboardNetwork

version: '3'

services:
  adventure_works_dashboard_dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 8501:8501
    
    environment:
      - DATABASE_SERVER=AdventureWorksDashboardSQLServer
      - DATABASE_NAME=AdventureWorksDW2019
      - DATABASE_USERNAME=SA
      - DATABASE_PASSWORD=my_ShittyPassword123
    networks:
      - AdventureWorksDashboardNetwork

  AdventureWorksDashboardSQLServer:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=my_ShittyPassword123
    container_name: AdventureWorksDashboardSQLServer
    hostname: AdventureWorksDashboardSQLServer
    ports:
      - 1433:1433
    networks:
      - AdventureWorksDashboardNetwork
  
networks:
  AdventureWorksDashboardNetwork:
    driver: bridge

# networks:
#   AdventureWorksDashboardNetwork:
#     external: true

